import { join } from "node:path";
import { readIfExists } from "../internals/fsxn.js";
import type { PlanContext } from "../internals/plan.js";

/**
 * The append-only usage event log behind `aih report`'s usage analytics. Events
 * are written at runtime by capture hooks (a universal git `post-commit` hook now;
 * per-tool skill/MCP hooks next), one JSON object per line in `.aih/usage.jsonl`
 * (gitignored live data). This module only READS + aggregates — the recorder that
 * writes is generated by `aih usage` (see `capture.ts`).
 */

export const USAGE_PATH = join(".aih", "usage.jsonl");

/** A single recorded usage event. `kind` says what happened; the rest is optional. */
export interface UsageEvent {
  /** ISO timestamp the event was recorded (runtime wall-clock from the hook). */
  ts?: string;
  /** Which tool produced it: "git" (universal floor), or a CLI name (claude, …). */
  tool: string;
  /** commit (git activity) · skill · mcp · session · tool (generic tool call). */
  kind: "commit" | "skill" | "mcp" | "session" | "tool";
  /** Skill / command / MCP-tool name, when applicable. */
  name?: string;
  /** MCP server, for kind="mcp". */
  server?: string;
  /** Skill provenance, when the capturing hook can attribute it. */
  source?: "ecc" | "canon" | "user";
  /** Commit deltas, for kind="commit". */
  added?: number;
  removed?: number;
  files?: number;
  sha?: string;
  /** Commit branch (kind="commit"); captured going forward — older events lack it. */
  branch?: string;
}

const KINDS = new Set(["commit", "skill", "mcp", "session", "tool"]);

/** Read + parse `.aih/usage.jsonl`, skipping malformed/invalid lines. */
export function readUsage(ctx: PlanContext): UsageEvent[] {
  const raw = readIfExists(join(ctx.root, USAGE_PATH));
  if (!raw) return [];
  const out: UsageEvent[] = [];
  for (const line of raw.split(/\r?\n/)) {
    const t = line.trim();
    if (!t) continue;
    try {
      const e = JSON.parse(t) as UsageEvent;
      if (e && typeof e.tool === "string" && KINDS.has(e.kind)) out.push(e);
    } catch {
      // skip a malformed line rather than failing the whole read
    }
  }
  return out;
}
