import { join } from "node:path";
import { readIfExists } from "../internals/fsxn.js";
import type { PlanContext } from "../internals/plan.js";

/**
 * The append-only usage event log behind `aih report`'s usage analytics. Events
 * are written at runtime by capture hooks (a universal git `post-commit` hook now;
 * per-tool skill/MCP hooks next), one JSON object per line in `.aih/usage.jsonl`
 * (gitignored live data). This module only READS + aggregates — the recorder that
 * writes is generated by `aih usage` (see `capture.ts`).
 */

export const USAGE_PATH = ".aih/usage.jsonl";

/** Optional local token/cache counters. Omitted counters mean "not captured", not zeroed telemetry. */
export interface UsageTokens {
  input?: number;
  output?: number;
  cacheRead?: number;
  cacheCreation?: number;
}

/** A single recorded usage event. `kind` says what happened; the rest is optional. */
export interface UsageEvent {
  /** Stable local event id, when an importer can derive one without storing content. */
  id?: string;
  /** ISO timestamp the event was recorded (runtime wall-clock from the hook). */
  ts?: string;
  /** Which tool produced it: "git" (universal floor), or a CLI name (claude, …). */
  tool: string;
  /** commit (git activity) · skill · mcp · session · tool (generic tool call). */
  kind: "commit" | "skill" | "mcp" | "session" | "tool";
  /** Skill / command / MCP-tool name, when applicable. */
  name?: string;
  /** MCP server, for kind="mcp". */
  server?: string;
  /** Skill provenance, when the capturing hook can attribute it. */
  source?: "ecc" | "canon" | "user";
  /** Commit deltas, for kind="commit". */
  added?: number;
  removed?: number;
  files?: number;
  sha?: string;
  /** Commit branch (kind="commit"); captured going forward — older events lack it. */
  branch?: string;
  /** Local token/cache counters when a CLI hook can provide them. */
  tokens?: UsageTokens;
}

const KINDS = new Set<UsageEvent["kind"]>(["commit", "skill", "mcp", "session", "tool"]);
const SOURCES = new Set<NonNullable<UsageEvent["source"]>>(["ecc", "canon", "user"]);
type UsageSource = NonNullable<UsageEvent["source"]>;

function recordOf(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;
}

function optionalString(value: unknown): string | undefined | null {
  if (value === undefined) return undefined;
  return typeof value === "string" ? value : null;
}

function optionalCounter(value: unknown): number | undefined | null {
  if (value === undefined) return undefined;
  return typeof value === "number" && Number.isFinite(value) && value >= 0 ? value : null;
}

function parseTokens(value: unknown): UsageTokens | undefined | null {
  if (value === undefined) return undefined;
  const raw = recordOf(value);
  if (!raw) return null;
  const tokens: UsageTokens = {};
  const input = optionalCounter(raw.input);
  const output = optionalCounter(raw.output);
  const cacheRead = optionalCounter(raw.cacheRead);
  const cacheCreation = optionalCounter(raw.cacheCreation);
  if (input === null || output === null || cacheRead === null || cacheCreation === null) {
    return null;
  }
  if (input !== undefined) tokens.input = input;
  if (output !== undefined) tokens.output = output;
  if (cacheRead !== undefined) tokens.cacheRead = cacheRead;
  if (cacheCreation !== undefined) tokens.cacheCreation = cacheCreation;
  return Object.keys(tokens).length > 0 ? tokens : undefined;
}

function parseUsageEvent(value: unknown): UsageEvent | undefined {
  const raw = recordOf(value);
  if (!raw || typeof raw.tool !== "string" || !KINDS.has(raw.kind as UsageEvent["kind"])) {
    return undefined;
  }
  const event: UsageEvent = { tool: raw.tool, kind: raw.kind as UsageEvent["kind"] };

  const id = optionalString(raw.id);
  const name = optionalString(raw.name);
  const server = optionalString(raw.server);
  const ts = optionalString(raw.ts);
  const sha = optionalString(raw.sha);
  const branch = optionalString(raw.branch);
  const added = optionalCounter(raw.added);
  const removed = optionalCounter(raw.removed);
  const files = optionalCounter(raw.files);
  const tokens = parseTokens(raw.tokens);
  if (
    id === null ||
    name === null ||
    server === null ||
    ts === null ||
    sha === null ||
    branch === null ||
    added === null ||
    removed === null ||
    files === null ||
    tokens === null
  ) {
    return undefined;
  }

  const source = raw.source;
  if (source !== undefined) {
    if (typeof source !== "string" || !SOURCES.has(source as UsageSource)) return undefined;
    event.source = source as UsageSource;
  }
  if (id !== undefined) event.id = id;
  if (name !== undefined) event.name = name;
  if (server !== undefined) event.server = server;
  if (ts !== undefined) event.ts = ts;
  if (added !== undefined) event.added = added;
  if (removed !== undefined) event.removed = removed;
  if (files !== undefined) event.files = files;
  if (sha !== undefined) event.sha = sha;
  if (branch !== undefined) event.branch = branch;
  if (tokens !== undefined) event.tokens = tokens;
  return event;
}

/** Read + parse `.aih/usage.jsonl`, skipping malformed/invalid lines. */
export function readUsage(ctx: PlanContext): UsageEvent[] {
  const raw = readIfExists(join(ctx.root, USAGE_PATH));
  if (!raw) return [];
  const out: UsageEvent[] = [];
  for (const line of raw.split(/\r?\n/)) {
    const t = line.trim();
    if (!t) continue;
    try {
      const e = parseUsageEvent(JSON.parse(t));
      if (e) out.push(e);
    } catch {
      // skip a malformed line rather than failing the whole read
    }
  }
  return out;
}
