/**
 * Project Framework Binding v1 — W2 core (library only; no CLI registration).
 *
 * Layering: the committed declaration (`schema.ts`) is the authority; the lock
 * (`lock.ts`), source checkouts, and scan results (`scan-gate.ts`) are derived,
 * rebuildable machine state; adapters (`adapter.ts`) act through the one narrow
 * D6 contract and can only provision behind the brand-protected scan disposition.
 */

export {
  ADAPTER_TYPES,
  AdapterRegistry,
  type AdapterType,
  assertPlanAllowed,
  assertProvisionAllowed,
  BindingAdapterRegistryError,
  type BindingContext,
  type BindingPlan,
  type BindingReport,
  DEFERRED_ADAPTER_TYPES,
  type FrameworkAdapter,
  type InspectReport,
  type InspectRequest,
  type ProvisionRequest,
  type ProvisionResult,
  type RemoveResult,
  type ResolveRequest,
  type VerifyResult,
} from "./adapter.js";
// W3f — plan-time feature-key validation shared by every W4+ adapter.
export { assertKnownFeatureKeys, BindingFeatureKeyError } from "./features.js";
// W3 — Claude project-scope host adapter: detection, D18 managed writes/removal,
// plugin binding + D7 identity, skillOverrides deny lists (D11), contamination
// report, previewed cleanup with backup/rollback, and context-cost inventory.
export {
  applyClaudeCleanup,
  assertSafePluginName,
  type BindPluginDeps,
  type BindPluginRequest,
  type BindPluginResult,
  bindPlugin,
  CLAUDE_BINDING_MARKER,
  CLAUDE_BOOTLOADER_PATH,
  CLAUDE_MCP_PATH,
  CLAUDE_OWNED_FILE_ROOTS,
  CLAUDE_PLUGINS_CACHE_REL,
  CLAUDE_PLUGINS_CONFIG_REL,
  CLAUDE_PLUGINS_DIR_REL,
  CLAUDE_PLUGINS_MARKETPLACES_KEY,
  CLAUDE_SETTINGS_LOCAL_PATH,
  CLAUDE_SETTINGS_PATH,
  CLAUDE_SHARED_JSON_FILES,
  type ClaudeCleanupAction,
  type ClaudeCleanupApplyDeps,
  type ClaudeCleanupApplyResult,
  type ClaudeCleanupEdit,
  ClaudeCleanupError,
  type ClaudeCleanupManifest,
  type ClaudeCleanupPlan,
  type ClaudeCleanupPlanOptions,
  type ClaudeCleanupRollbackDeps,
  type ClaudeCleanupRollbackResult,
  type ClaudeCleanupStep,
  type ClaudeContaminationParams,
  type ClaudeContaminationReport,
  type ClaudeDriftEntry,
  type ClaudeHostDetectDeps,
  type ClaudeHostReport,
  ClaudeHostWriteError,
  type ClaudeManagedPlan,
  ClaudeManagedWriteEngine,
  type ClaudeOwnershipIntent,
  type ClaudeOwnershipKind,
  ClaudePluginCacheMissingError,
  ClaudePluginError,
  ClaudePluginIdentityError,
  type ClaudePreExisting,
  type ClaudeRemovalPlan,
  type ContaminationEntry,
  type ContaminationLeakage,
  type ContaminationSurface,
  type ContextCostEvidenceSource,
  type ContextCostReport,
  claudeContaminationReport,
  claudeHomeDir,
  contextCostFromPluginDetails,
  defaultPluginCacheLocator,
  detectClaudeHost,
  disablePlugin,
  enablePlugin,
  estimateContextCostFromTree,
  type FrameworkAttribution,
  finalizeClaudeOwnership,
  HOME_OWNERSHIP_PREFIX,
  hashLoadedPluginTree,
  homeMarketplaceTarget,
  homePluginCacheTarget,
  installPlugin,
  isHomeScopedTarget,
  listPlugins,
  marketplaceAdd,
  marketplaceRemove,
  type PinnedSkillInventory,
  type PluginCacheLocator,
  type PluginCacheLocatorParams,
  type PluginCliDeps,
  type PluginIdentity,
  type PluginScope,
  planClaudeCleanup,
  planClaudeRemoval,
  pluginDetails,
  pluginEnableKey,
  queueSkillDenyList,
  type RemovePluginDeps,
  type RemovePluginRequest,
  type RemovePluginResult,
  removePlugin,
  rollbackClaudeCleanup,
  type SkillDenyListReport,
  settingsFileForScope,
  skillDenyListReport,
  uninstallPlugin,
  verifyPluginIdentity,
} from "./hosts/claude/index.js";
export {
  type BindingLock,
  BindingLockError,
  type BindingLockRead,
  BindingLockSchema,
  type BindingOwnershipEntry,
  BindingOwnershipEntrySchema,
  type BindingRemovalPlan,
  type BindingWrite,
  BindingWriteSchema,
  bindingDir,
  bindingLockPath,
  parseBindingLock,
  planBindingRemoval,
  readBindingLock,
  writeBindingLockAtomic,
} from "./lock.js";
export {
  acquireNpmTree,
  assertProvisionAuthorized,
  assertResolvedMatchesDeclaration,
  BindingNotSupportedError,
  BindingScanError,
  bindingCacheHome,
  type DimensionInspectionContext,
  type DimensionInspector,
  type DimensionReport,
  type FastScanDeps,
  type FastScanPolicy,
  type GitResolveDeps,
  type GitResolveRequest,
  type InspectTreeDeps,
  inspectTree,
  type NpmMetadataFetcher,
  type NpmRegistryMetadata,
  type NpmResolveRequest,
  type ResolvedGitSource,
  type ResolvedNpmSource,
  type ResolvedSource,
  resolvedSourceDigest,
  resolveGitSource,
  resolveNpmSource,
  runFastScanGate,
  type ScanCoverage,
  type ScanDisposition,
  type ScanFinding,
  type ScannableSource,
  type ScanSeverity,
  type ScanVerdict,
  scannableFromGit,
  W2_DEFAULT_INSPECTORS,
} from "./scan-gate.js";
export {
  assertSingleMethodologyFramework,
  BINDING_HOSTS,
  BINDING_SCHEMA_VERSION,
  type BindingDeclaration,
  BindingDeclarationError,
  BindingDeclarationSchema,
  type BindingFramework,
  BindingFrameworkConflictError,
  BindingFrameworkSchema,
  type BindingGitSource,
  BindingGitSourceSchema,
  type BindingNpmSource,
  BindingNpmSourceSchema,
  type BindingSource,
  BindingSourceSchema,
  FRAMEWORK_IDS,
  type FrameworkId,
  parseBindingDeclaration,
  readBindingDeclaration,
  safeParseBindingDeclaration,
} from "./schema.js";
