/**
 * Project Framework Binding v1 — W2 core (library only; no CLI registration).
 *
 * Layering: the committed declaration (`schema.ts`) is the authority; the lock
 * (`lock.ts`), source checkouts, and scan results (`scan-gate.ts`) are derived,
 * rebuildable machine state; adapters (`adapter.ts`) act through the one narrow
 * D6 contract and can only provision behind the brand-protected scan disposition.
 */

export {
  ADAPTER_TYPES,
  AdapterRegistry,
  type AdapterType,
  assertPlanAllowed,
  assertProvisionAllowed,
  BindingAdapterRegistryError,
  type BindingContext,
  type BindingPlan,
  type BindingReport,
  DEFERRED_ADAPTER_TYPES,
  type FrameworkAdapter,
  type InspectReport,
  type InspectRequest,
  type ProvisionRequest,
  type ProvisionResult,
  type RemoveResult,
  type ResolveRequest,
  type VerifyResult,
} from "./adapter.js";
// W5 — the selected-profile closure classifier (a2). The scan gate consumes this
// to separate the executed/loaded runtime closure from materialized-inert source.
export {
  CLOSURE_CLASSIFIER_VERSION,
  type ClosureInput,
  type ClosureNode,
  type ClosureSeed,
  type ClosureSpec,
  classificationOf,
  classifyClosure,
  type FindingClassification,
  FULL_TREE_PROFILE,
  fullTreeClosureSpec,
  type HostLoadFacts,
  type ProfileClosure,
  type Reachability,
} from "./closure/profile-closure.js";
// W3f — plan-time feature-key validation shared by every W4+ adapter.
export { assertKnownFeatureKeys, BindingFeatureKeyError } from "./features.js";
// W4d — D10 cost-gate measurement record + ECC doctor rules.
export {
  buildCostGateRecord,
  type CostGateBudget,
  type CostGateRecord,
  type CostGateVariant,
  type CostGateVariantMeasurement,
  type CostGateVerdict,
  measureCostGateVariant,
} from "./frameworks/cost-gate.js";
// W4b — the ECC Lean adapter (upstream-local-installer). Composes the shipped,
// pin-bound ECC install-preview + an injected selective-install seam; adds no ECC
// install machinery of its own (D9). W4c adds the Full variant to the same file.
export {
  componentInstallRoot,
  computeEccFullLabel,
  computeEccLeanPreviewDiff,
  createEccAdapter,
  ECC_AGENT_DATA_HOME_DEFAULT,
  ECC_FULL_FEATURE_KEYS,
  ECC_FULL_MARKETPLACE_NAME,
  ECC_FULL_MCP_CONNECTORS,
  ECC_FULL_PLUGIN_NAME,
  ECC_HOMUNCULUS_DIR_DEFAULT,
  ECC_HOST_TARGET,
  ECC_LEAN_ACCEPTANCE_TUPLE,
  ECC_LEAN_ALLOWLIST,
  ECC_LEAN_EXCLUDED,
  ECC_PIN_COMMIT,
  ECC_REPOSITORY,
  EccBindingError,
  type EccFullLabelInput,
  type EccFullProvisionResult,
  type EccFullRemoveResult,
  type EccLeanAdapterDeps,
  EccLeanAllowlistError,
  type EccLeanInstalledFile,
  type EccLeanInstaller,
  EccLeanInstallerUnavailableError,
  type EccLeanInstallInput,
  type EccLeanInstallResult,
  type EccLeanManifest,
  type EccLeanPreviewDiff,
  type EccLeanRemoveResult,
  type EccMode,
  EccModeConflictError,
  EccModeNotImplementedError,
  type EccStateWriteFinding,
  eccFullStateWriteInventory,
  eccLeanManifest,
  eccRuntimeSurfaceHit,
  type NormalizedEccOp,
  normalizeEccOperations,
} from "./frameworks/ecc.js";
export { eccDoubleInstallCheck, eccModeExclusivityCheck } from "./frameworks/ecc-doctor.js";
// W4a — the first real D6 adapter (Superpowers, host-plugin) + its registry
// assembly point. Composes the W3 Claude host services above; adds no new
// host mechanism of its own.
export {
  type BindingRegistryDeps,
  createBindingAdapterRegistry,
} from "./frameworks/registry.js";
export {
  createSuperpowersAdapter,
  SUPERPOWERS_MARKETPLACE_NAME,
  SUPERPOWERS_PIN_COMMIT,
  SUPERPOWERS_PLUGIN_NAME,
  SUPERPOWERS_REPOSITORY,
  type SuperpowersAdapterDeps,
  SuperpowersBindingError,
  type SuperpowersRemoveResult,
} from "./frameworks/superpowers.js";
// W3 — Claude project-scope host adapter: detection, D18 managed writes/removal,
// plugin binding + D7 identity, skillOverrides deny lists (D11), contamination
// report, previewed cleanup with backup/rollback, and context-cost inventory.
export {
  applyClaudeCleanup,
  assertSafePluginName,
  type BindPluginDeps,
  type BindPluginRequest,
  type BindPluginResult,
  bindPlugin,
  CLAUDE_BINDING_MARKER,
  CLAUDE_BOOTLOADER_PATH,
  CLAUDE_EXTRA_KNOWN_MARKETPLACES_KEY,
  CLAUDE_HOME_SETTINGS_REL,
  CLAUDE_MCP_PATH,
  CLAUDE_OWNED_FILE_ROOTS,
  CLAUDE_PLUGINS_CACHE_REL,
  CLAUDE_PLUGINS_DIR_REL,
  CLAUDE_SETTINGS_LOCAL_PATH,
  CLAUDE_SETTINGS_PATH,
  CLAUDE_SHARED_JSON_FILES,
  type ClaudeCleanupAction,
  type ClaudeCleanupApplyDeps,
  type ClaudeCleanupApplyResult,
  type ClaudeCleanupEdit,
  ClaudeCleanupError,
  type ClaudeCleanupManifest,
  type ClaudeCleanupPlan,
  type ClaudeCleanupPlanOptions,
  type ClaudeCleanupRollbackDeps,
  type ClaudeCleanupRollbackResult,
  type ClaudeCleanupStep,
  type ClaudeContaminationParams,
  type ClaudeContaminationReport,
  type ClaudeDriftEntry,
  type ClaudeHostDetectDeps,
  type ClaudeHostReport,
  ClaudeHostWriteError,
  type ClaudeManagedPlan,
  ClaudeManagedWriteEngine,
  type ClaudeOwnershipIntent,
  type ClaudeOwnershipKind,
  ClaudePluginCacheMissingError,
  ClaudePluginError,
  ClaudePluginIdentityError,
  type ClaudePreExisting,
  type ClaudeRemovalPlan,
  type ContaminationEntry,
  type ContaminationLeakage,
  type ContaminationSurface,
  type ContextCostEvidenceSource,
  type ContextCostReport,
  carryForwardOwnership,
  claudeContaminationReport,
  claudeHomeDir,
  contextCostFromPluginDetails,
  contextCostFromPluginDetailsText,
  defaultPluginCacheLocator,
  detectClaudeHost,
  disablePlugin,
  enablePlugin,
  estimateContextCostFromTree,
  type FrameworkAttribution,
  finalizeClaudeOwnership,
  HOME_OWNERSHIP_PREFIX,
  hashLoadedPluginTree,
  homeMarketplaceTarget,
  homePluginCacheTarget,
  installPathFromPluginList,
  installPlugin,
  isHomeScopedTarget,
  listPlugins,
  marketplaceAdd,
  marketplaceRemove,
  type PinnedSkillInventory,
  type PluginCacheLocator,
  type PluginCacheLocatorParams,
  type PluginCliDeps,
  type PluginIdentity,
  type PluginScope,
  type PluginSourceSubtree,
  planClaudeCleanup,
  planClaudeRemoval,
  pluginDetails,
  pluginEnableKey,
  pluginSourceSubtreeDigest,
  queueSkillDenyList,
  type RemovePluginDeps,
  type RemovePluginRequest,
  type RemovePluginResult,
  removePlugin,
  rollbackClaudeCleanup,
  type SkillDenyListReport,
  settingsFileForScope,
  skillDenyListReport,
  uninstallPlugin,
  verifyPluginIdentity,
} from "./hosts/claude/index.js";
export {
  type BindingLock,
  BindingLockError,
  type BindingLockRead,
  BindingLockSchema,
  type BindingOwnershipEntry,
  BindingOwnershipEntrySchema,
  type BindingRemovalPlan,
  type BindingWrite,
  BindingWriteSchema,
  bindingDir,
  bindingLockPath,
  parseBindingLock,
  planBindingRemoval,
  readBindingLock,
  writeBindingLockAtomic,
} from "./lock.js";
export {
  type AcceptedContentFinding,
  acquireNpmTree,
  assertProvisionAuthorized,
  assertResolvedMatchesDeclaration,
  BindingNotSupportedError,
  BindingScanError,
  bindingCacheHome,
  type DimensionInspectionContext,
  type DimensionInspector,
  type DimensionReport,
  type FastScanDeps,
  type FastScanPolicy,
  type FrameworkCardDisclosure,
  type GitResolveDeps,
  type GitResolveRequest,
  type InspectTreeDeps,
  inspectTree,
  type NpmMetadataFetcher,
  type NpmRegistryMetadata,
  type NpmResolveRequest,
  type RawSourceOutcome,
  type ResolvedGitSource,
  type ResolvedNpmSource,
  type ResolvedSource,
  readScanAcceptanceArtifact,
  resolvedSourceDigest,
  resolveGitSource,
  resolveNpmSource,
  runFastScanGate,
  type ScanAcceptanceArtifact,
  type ScanAcceptanceReport,
  type ScanCoverage,
  type ScanDisposition,
  type ScanFinding,
  type ScannableSource,
  type ScanSeverity,
  type ScanVerdict,
  type SelectedProfileGate,
  scanAcceptanceReport,
  scannableFromGit,
  W2_DEFAULT_INSPECTORS,
} from "./scan-gate.js";
export {
  assertSingleMethodologyFramework,
  BINDING_HOSTS,
  BINDING_SCHEMA_VERSION,
  type BindingDeclaration,
  BindingDeclarationError,
  BindingDeclarationSchema,
  type BindingFramework,
  BindingFrameworkConflictError,
  BindingFrameworkSchema,
  type BindingGitSource,
  BindingGitSourceSchema,
  type BindingNpmSource,
  BindingNpmSourceSchema,
  type BindingSource,
  BindingSourceSchema,
  FRAMEWORK_IDS,
  type FrameworkId,
  parseBindingDeclaration,
  readBindingDeclaration,
  safeParseBindingDeclaration,
} from "./schema.js";
// W5 rule-8 — gate-layer visible-typography reclassifier (advisory demotion of
// hidden-unicode findings whose file is all prose/comment/human-string typography).
export {
  classifyFileTypography,
  enumerateTypography,
  type FileTypographyVerdict,
  type TypographyAdvisory,
  type TypographyOccurrence,
} from "./visible-typography.js";
