import { baselineCatalogById } from "../baseline-evidence/catalogs.js";
import type { BaselineAuthorization } from "../baseline-evidence/verify.js";
import type { Cli } from "../internals/clis.js";
import { digest, doc, type Plan, type PlanContext, plan, writeText } from "../internals/plan.js";
import { lines } from "../internals/render.js";
import { methodologySteering } from "../kiro/content.js";
import { superpowersActionsForCli, superpowersOverviewDoc } from "./install.js";

export function superpowersEvidenceComponentIds(): string[] {
  return baselineCatalogById("superpowers").components.map((component) => component.id);
}

export function verifiedSuperpowersInstallPlan(
  _ctx: PlanContext,
  sourceRoot: string,
  clis: Cli[],
  authorizations: readonly BaselineAuthorization[],
): Plan {
  const pin = authorizations[0]?.pinnedSha ?? baselineCatalogById("superpowers").pinnedSha;
  const actions = clis.flatMap((cli) => superpowersActionsForCli(cli, pin));
  if (clis.includes("kiro")) {
    actions.push(
      writeText(
        ".kiro/steering/superpowers-methodology.md",
        methodologySteering(),
        "Kiro steering: first-party aih methodology bridge (not Superpowers vendor bytes)",
      ),
      doc(
        "Kiro methodology bridge provenance",
        "The Kiro steering file is generated by aih and is not labeled as obra/Superpowers vendor evidence.",
      ),
    );
  }
  actions.push(
    superpowersOverviewDoc(),
    doc(
      "Superpowers verified source",
      `aih verified the selected components from ${sourceRoot.replace(/\\/g, "/")} at exact commit ${pin}; the quarantine is removed after this command.`,
    ),
    digest(
      "Superpowers baseline evidence authorizations",
      lines(
        "Superpowers component evidence receipts:",
        ...authorizations.map(
          (receipt) =>
            `- ${receipt.componentId} — ${receipt.tier} · ${receipt.pinnedSha.slice(0, 12)} · ${receipt.treeSha256.slice(0, 12)}`,
        ),
      ),
      { authorizations: [...authorizations] },
    ),
  );
  return plan("superpowers: verified guidance", ...actions);
}
