import { createHash, randomBytes } from "node:crypto";
import {
  type BigIntStats,
  chmodSync,
  closeSync,
  copyFileSync,
  existsSync,
  constants as fsConstants,
  fstatSync,
  fsyncSync,
  lstatSync,
  mkdirSync,
  openSync,
  readdirSync,
  readFileSync,
  readSync,
  renameSync,
  rmdirSync,
  rmSync,
  type Stats,
  writeFileSync,
} from "node:fs";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { FsTxnError } from "../errors.js";

/**
 * Transient Windows file-lock error codes. On Windows an antivirus scanner or the
 * Search indexer opens a file the instant it appears, so a `copyFile`/`rename`/
 * `read` issued microseconds after a write can fail with one of these and then
 * succeed on the very next attempt — the "failed on CI, passed on a re-run"
 * signature. POSIX does not raise these for our in-process, same-volume sync
 * operations, so {@link retryTransient} is a no-op there.
 */
const TRANSIENT_LOCK_CODES = new Set(["EBUSY", "EPERM", "EACCES"]);
const MAX_LOCK_RETRIES = 10;

/** Sleep the current thread synchronously (every fs call below is sync). */
function sleepSync(ms: number): void {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

/**
 * Run a synchronous fs operation, retrying ONLY the transient Windows lock codes
 * in {@link TRANSIENT_LOCK_CODES} with a short bounded backoff (~0.5s worst case).
 * Any other error — `EEXIST` from an exclusive create, a genuine `EACCES` on a
 * locked-down path that never clears — is re-thrown on its first occurrence, so
 * this absorbs the sub-millisecond scanner window without ever masking a real
 * failure. The retry preserves the caller's atomicity/rollback guarantees: it
 * re-issues the same single syscall, nothing more.
 *
 * Exported for direct unit testing — the FS-level retry is exercised through the
 * real filesystem elsewhere, but a transient lock cannot be reproduced on demand,
 * so the retry/give-up/passthrough contract is pinned here.
 */
export function retryTransient<T>(op: () => T): T {
  let delayMs = 1;
  for (let attempt = 1; ; attempt++) {
    try {
      return op();
    } catch (err) {
      const code = (err as NodeJS.ErrnoException).code;
      const transient = code !== undefined && TRANSIENT_LOCK_CODES.has(code);
      if (!transient || attempt >= MAX_LOCK_RETRIES) throw err;
      sleepSync(delayMs);
      delayMs = Math.min(delayMs * 2, 100);
    }
  }
}

interface StagedWrite {
  path: string;
  contents: string;
  mode?: number;
  expect?: { absent: true } | { sha256: string };
  root?: string;
  durable?: boolean;
}

export interface AppliedWrite {
  path: string;
  contents: string;
  backup?: string;
  created: boolean;
  parentGuard?: ParentGuard;
}

/** A file to remove by MOVING it to `legacyPath` (under gitignored `.aih/legacy/`). */
interface StagedRemoval {
  path: string;
  legacyPath: string;
  /**
   * Backup-sibling destination (hard-delete's `<path>.aih.bak`). Like the default
   * `.aih/legacy/` archive it NEVER overwrites an occupied destination — an existing
   * `.aih.bak` may be the ONLY copy of prior content (a removal backup is not like a
   * write backup, whose content also survives in the replaced file). A taken slot
   * falls back to `<path>.1.aih.bak`, `<path>.2.aih.bak`, … which still match the
   * gitignored `*.aih.bak` glob.
   */
  backupSibling?: boolean;
  expect?: { sha256: string };
  root?: string;
}

interface AppliedRemoval {
  path: string;
  legacyPath: string;
  sourceParentGuard?: ParentGuard;
  legacyParentGuard?: ParentGuard;
}

interface StagedAssertion {
  path: string;
  sha256: string;
  describe: string;
  root?: string;
}

interface DirectoryIdentity {
  dev: bigint;
  ino: bigint;
}

export interface ParentGuard {
  directories: readonly ({ path: string } & DirectoryIdentity)[];
}

interface CommitLock {
  path: string;
  root: string;
  /** Internal bounded lease for a synchronous transaction. */
  leaseMs?: number;
}

interface CommitLease {
  expiresAt: number;
  reclaimAfter: number;
  owner: string;
}

interface OwnedCommitLease extends CommitLease, DirectoryIdentity {
  activePath: string;
  anchorDev: bigint;
  anchorIno: bigint;
  leaseDev: bigint;
  leaseIno: bigint;
  leasePath: string;
  leaseText: string;
}

interface FsTransactionOptions {
  commitNotAfter?: number;
  commitLock?: CommitLock;
}

export interface FsTxnResult {
  written: string[];
  backups: string[];
  /** Files moved out of the tree (source → `.aih/legacy/` destination). */
  removed: AppliedRemoval[];
}

/**
 * Stages writes in memory and commits them atomically. Each existing target is
 * first copied to `<path>.aih.bak`; new content is written to a temp file and
 * `rename`d into place (atomic on the same volume). If a later write throws,
 * targets that still hold this transaction's generated bytes are rolled back;
 * a concurrently changed target is preserved along with its backup.
 */
export class FsTransaction {
  private staged: StagedWrite[] = [];
  private stagedRemovals: StagedRemoval[] = [];
  private stagedAssertions: StagedAssertion[] = [];
  private readonly guardedDirectories = new Map<string, DirectoryIdentity>();
  private readonly createdDirectories = new Map<string, DirectoryIdentity>();
  private activeCommitLease: OwnedCommitLease | undefined;

  constructor(private readonly options: FsTransactionOptions = {}) {}

  stage(
    path: string,
    contents: string,
    mode?: number,
    expect?: { absent: true } | { sha256: string },
    opts: { root?: string; durable?: boolean } = {},
  ): void {
    this.staged.push({ path, contents, mode, expect, root: opts.root, durable: opts.durable });
  }

  /**
   * Stage a file REMOVAL as a reversible move to `legacyPath` (under gitignored
   * `.aih/legacy/`). The move IS the backup: rollback (and the user) restore by
   * moving it back. Symlinks are refused at commit (moving a link then restoring it
   * would recreate a regular file). No-op if the source is already gone.
   * `backupSibling` marks a hard-delete destination (`<path>.aih.bak`): still
   * never-overwrite, but a taken slot falls back to `<path>.N.aih.bak` (matches the
   * gitignored `*.aih.bak` glob) instead of the archive's `<path>.N`.
   */
  stageRemoval(
    path: string,
    legacyPath: string,
    opts: { backupSibling?: boolean; expect?: { sha256: string }; root?: string } = {},
  ): void {
    this.stagedRemovals.push({
      path,
      legacyPath,
      backupSibling: opts.backupSibling,
      expect: opts.expect,
      root: opts.root,
    });
  }

  stageAssertion(path: string, sha256: string, describe: string, root?: string): void {
    this.stagedAssertions.push({ path, sha256, describe, root });
  }

  preview(): ReadonlyArray<StagedWrite> {
    return [...this.staged];
  }

  private assertCommitDeadline(): void {
    if (this.options.commitNotAfter !== undefined && Date.now() >= this.options.commitNotAfter) {
      throw new FsTxnError("commit deadline expired");
    }
    const active = this.activeCommitLease;
    const lock = this.options.commitLock;
    if (active === undefined || lock === undefined) return;
    if (Date.now() >= active.expiresAt) throw new FsTxnError("commit lock lease expired");
    if (!this.sameLease(active, this.activeLease(lock)))
      throw new FsTxnError("commit lock lease lost");
  }

  private assertRollbackLease(): void {
    const active = this.activeCommitLease;
    const lock = this.options.commitLock;
    if (active === undefined || lock === undefined) return;
    if (Date.now() >= active.reclaimAfter)
      throw new FsTxnError("commit lock lease recovery window expired");
    if (!this.sameLease(active, this.activeLease(lock)))
      throw new FsTxnError("commit lock lease lost");
  }

  private identity(path: string): DirectoryIdentity {
    let stats: BigIntStats;
    try {
      stats = lstatSync(path, { bigint: true });
    } catch {
      throw new FsTxnError("unsafe transaction parent path");
    }
    if (!stats.isDirectory() || stats.isSymbolicLink() || stats.dev === 0n || stats.ino === 0n) {
      throw new FsTxnError("unsafe transaction parent path");
    }
    return { dev: stats.dev, ino: stats.ino };
  }

  private sameDirectory(path: string, expected: DirectoryIdentity): boolean {
    try {
      const actual = this.identity(path);
      return actual.dev === expected.dev && actual.ino === expected.ino;
    } catch {
      return false;
    }
  }

  private guardParents(path: string, root: string | undefined, create: boolean): void {
    if (root === undefined) return;
    this.assertCommitDeadline();
    const base = resolve(root);
    const parent = resolve(dirname(path));
    const rel = relative(base, parent);
    if (rel.startsWith("..") || isAbsolute(rel))
      throw new FsTxnError("unsafe transaction parent path");
    const parts = rel === "" ? [] : rel.split(/[\\/]+/).filter((part) => part.length > 0);
    let current = base;
    const capture = (dir: string, created = false): void => {
      this.assertCommitDeadline();
      const actual = this.identity(dir);
      const prior = this.guardedDirectories.get(dir);
      if (prior !== undefined && (prior.dev !== actual.dev || prior.ino !== actual.ino)) {
        throw new FsTxnError("unsafe transaction parent path");
      }
      this.guardedDirectories.set(dir, actual);
      if (created) this.createdDirectories.set(dir, actual);
    };
    capture(current);
    for (const part of parts) {
      current = resolve(current, part);
      try {
        capture(current);
      } catch (err) {
        if (!create) throw err;
        this.assertCommitDeadline();
        try {
          mkdirSync(current);
        } catch {
          throw new FsTxnError("unsafe transaction parent path");
        }
        capture(current, true);
      }
    }
  }

  private ensureParents(path: string, root: string | undefined): void {
    if (root === undefined) {
      this.assertCommitDeadline();
      mkdirSync(dirname(path), { recursive: true });
      return;
    }
    this.guardParents(path, root, true);
  }

  private captureParentGuard(path: string, root: string | undefined): ParentGuard | undefined {
    if (root === undefined) return undefined;
    this.guardParents(path, root, false);
    const base = resolve(root);
    const parent = resolve(dirname(path));
    const rel = relative(base, parent);
    if (rel.startsWith("..") || isAbsolute(rel))
      throw new FsTxnError("unsafe transaction parent path");
    const directories: ({ path: string } & DirectoryIdentity)[] = [];
    let current = base;
    const add = (): void => {
      const identity = this.guardedDirectories.get(current);
      if (identity === undefined) throw new FsTxnError("unsafe transaction parent path");
      directories.push({ path: current, ...identity });
    };
    add();
    for (const part of rel.split(/[\\/]+/).filter((item) => item.length > 0)) {
      current = resolve(current, part);
      add();
    }
    return { directories };
  }

  private rollbackCreatedDirectories(assertCanMutate: () => void = () => {}): void {
    for (const [path, identity] of [...this.createdDirectories.entries()].sort(
      ([left], [right]) => right.length - left.length,
    )) {
      try {
        if (this.sameDirectory(path, identity)) {
          assertCanMutate();
          rmdirSync(path);
        }
      } catch {
        // Do not remove a concurrently repopulated or replaced directory.
      }
    }
  }

  private static readonly commitLeaseMs = 30_000;
  private static readonly recoveryGraceMs = FsTransaction.commitLeaseMs;
  private static readonly maxStagingClaims = 32;
  private static readonly anchorText = '{"format":"aih-fs-commit-lock-anchor","version":1}';

  private leaseContents(lease: CommitLease): string {
    return JSON.stringify({
      expiresAt: lease.expiresAt,
      format: "aih-fs-commit-lease",
      owner: lease.owner,
      reclaimAfter: lease.reclaimAfter,
      version: 1,
    });
  }

  private parseLease(contents: string): CommitLease | undefined {
    try {
      const value = JSON.parse(contents) as Record<string, unknown>;
      const keys = Object.keys(value).sort();
      if (
        keys.length !== 5 ||
        keys.join(",") !== "expiresAt,format,owner,reclaimAfter,version" ||
        value.format !== "aih-fs-commit-lease" ||
        value.version !== 1 ||
        typeof value.expiresAt !== "number" ||
        !Number.isSafeInteger(value.expiresAt) ||
        typeof value.reclaimAfter !== "number" ||
        !Number.isSafeInteger(value.reclaimAfter) ||
        value.reclaimAfter - value.expiresAt !== FsTransaction.recoveryGraceMs ||
        typeof value.owner !== "string" ||
        !/^[0-9a-f]{64}$/.test(value.owner)
      )
        return undefined;
      const lease = {
        expiresAt: value.expiresAt,
        reclaimAfter: value.reclaimAfter,
        owner: value.owner,
      };
      return this.leaseContents(lease) === contents ? lease : undefined;
    } catch {
      return undefined;
    }
  }

  private anchorPath(lock: CommitLock): string {
    return lock.path;
  }

  private activePath(lock: CommitLock): string {
    return join(this.anchorPath(lock), "active");
  }

  private stagingPath(lock: CommitLock): string {
    return join(this.anchorPath(lock), "staging");
  }

  private leasePath(activePath: string, owner: string): string {
    return join(activePath, `lease.${owner}.json`);
  }

  private stagingName(lease: CommitLease): string {
    return `${lease.expiresAt}.${lease.reclaimAfter}.${lease.owner}`;
  }

  private parseStagingName(name: string): CommitLease | undefined {
    const match = /^(\d+)\.(\d+)\.([0-9a-f]{64})$/.exec(name);
    if (match === null) return undefined;
    const expiresAt = Number(match[1]);
    const reclaimAfter = Number(match[2]);
    const owner = match[3];
    if (
      !Number.isSafeInteger(expiresAt) ||
      !Number.isSafeInteger(reclaimAfter) ||
      reclaimAfter - expiresAt !== FsTransaction.recoveryGraceMs ||
      owner === undefined
    )
      return undefined;
    return { expiresAt, reclaimAfter, owner };
  }

  private directoryIdentity(path: string): DirectoryIdentity | undefined {
    try {
      const stats = lstatSync(path, { bigint: true });
      return stats.isDirectory() && !stats.isSymbolicLink() && stats.dev !== 0n && stats.ino !== 0n
        ? { dev: stats.dev, ino: stats.ino }
        : undefined;
    } catch {
      return undefined;
    }
  }

  private syncLeasePath(path: string, directory = false): void {
    if (directory && process.platform === "win32") return;
    const fd = openSync(path, directory ? fsConstants.O_RDONLY : fsConstants.O_RDWR);
    try {
      fsyncSync(fd);
    } finally {
      closeSync(fd);
    }
  }

  private ensureAnchor(lock: CommitLock): void {
    this.guardParents(lock.path, lock.root, true);
    const existing = lstatSafe(lock.path);
    if (existing === undefined) {
      const candidate = `${lock.path}.aih.anchor.${randomBytes(32).toString("hex")}`;
      const marker = join(candidate, "anchor.json");
      try {
        mkdirSync(candidate, 0o700);
        writeFileSync(marker, FsTransaction.anchorText, {
          encoding: "utf8",
          flag: "wx",
          mode: 0o600,
        });
        const markerInfo = lstatSync(marker, { bigint: true });
        if (!markerInfo.isFile() || markerInfo.isSymbolicLink() || markerInfo.nlink !== 1n)
          throw new FsTxnError("commit lock could not be verified");
        this.syncLeasePath(marker);
        this.syncLeasePath(candidate, true);
        renameSync(candidate, lock.path);
        this.syncLeasePath(dirname(lock.path), true);
      } catch {
        try {
          const markerInfo = lstatSync(marker, { bigint: true });
          if (markerInfo.isFile() && !markerInfo.isSymbolicLink() && markerInfo.nlink === 1n) {
            rmSync(marker);
            rmdirSync(candidate);
          }
        } catch {
          // Owner-specific pre-anchor staging never authorizes effects.
        }
        throw new FsTxnError("commit lock could not be verified");
      }
    }
    const identity = this.directoryIdentity(lock.path);
    const marker = join(lock.path, "anchor.json");
    try {
      const markerInfo = lstatSync(marker, { bigint: true });
      if (
        identity === undefined ||
        !markerInfo.isFile() ||
        markerInfo.isSymbolicLink() ||
        markerInfo.nlink !== 1n ||
        readFileSync(marker, "utf8") !== FsTransaction.anchorText
      )
        throw new FsTxnError("commit lock could not be verified");
      const names = readdirSync(lock.path).sort();
      if (names.some((name) => name !== "active" && name !== "anchor.json" && name !== "staging"))
        throw new FsTxnError("commit lock could not be verified");
      for (const name of ["active", "staging"] as const) {
        const entry = join(lock.path, name);
        if (lstatSafe(entry) !== undefined && this.directoryIdentity(entry) === undefined)
          throw new FsTxnError("commit lock could not be verified");
      }
    } catch (err) {
      if (err instanceof FsTxnError) throw err;
      throw new FsTxnError("commit lock could not be verified");
    }
  }

  private activeLease(lock: CommitLock): OwnedCommitLease | undefined {
    const anchor = this.directoryIdentity(this.anchorPath(lock));
    if (anchor === undefined) return undefined;
    try {
      const marker = lstatSync(join(this.anchorPath(lock), "anchor.json"), { bigint: true });
      if (
        !marker.isFile() ||
        marker.isSymbolicLink() ||
        marker.nlink !== 1n ||
        readFileSync(join(this.anchorPath(lock), "anchor.json"), "utf8") !==
          FsTransaction.anchorText
      )
        return undefined;
    } catch {
      return undefined;
    }
    const activePath = this.activePath(lock);
    const active = this.directoryIdentity(activePath);
    if (active === undefined) return undefined;
    let names: string[];
    try {
      names = readdirSync(activePath).sort();
    } catch {
      return undefined;
    }
    const name = names[0];
    if (names.length !== 1 || name === undefined || !/^lease\.[0-9a-f]{64}\.json$/.test(name))
      return undefined;
    const leasePath = join(activePath, name);
    let leaseText: string;
    let leaseDev: bigint;
    let leaseIno: bigint;
    try {
      const stats = lstatSync(leasePath, { bigint: true });
      if (!stats.isFile() || stats.isSymbolicLink() || stats.nlink !== 1n) return undefined;
      leaseText = readFileSync(leasePath, "utf8");
      leaseDev = stats.dev;
      leaseIno = stats.ino;
    } catch {
      return undefined;
    }
    const parsed = this.parseLease(leaseText);
    if (parsed === undefined || name !== `lease.${parsed.owner}.json`) return undefined;
    return {
      ...parsed,
      ...active,
      activePath,
      anchorDev: anchor.dev,
      anchorIno: anchor.ino,
      leaseDev,
      leaseIno,
      leasePath,
      leaseText,
    };
  }

  private sameLease(left: OwnedCommitLease, right: OwnedCommitLease | undefined): boolean {
    return (
      right !== undefined &&
      left.owner === right.owner &&
      left.expiresAt === right.expiresAt &&
      left.reclaimAfter === right.reclaimAfter &&
      left.dev === right.dev &&
      left.ino === right.ino &&
      left.anchorDev === right.anchorDev &&
      left.anchorIno === right.anchorIno &&
      left.leaseDev === right.leaseDev &&
      left.leaseIno === right.leaseIno &&
      left.leasePath === right.leasePath &&
      left.leaseText === right.leaseText
    );
  }

  private removeOwnedActive(lock: CommitLock, owned: OwnedCommitLease): boolean {
    if (!this.sameLease(owned, this.activeLease(lock))) return false;
    try {
      rmSync(owned.leasePath);
      rmdirSync(owned.activePath);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * A live owner is always represented by a non-empty active directory. An
   * empty one is only an interrupted owner-specific cleanup, so removing it
   * cannot delete a successor; any raced promotion makes rmdir fail.
   */
  private removeEmptyActive(lock: CommitLock): boolean {
    const activePath = this.activePath(lock);
    const identity = this.directoryIdentity(activePath);
    if (identity === undefined) return false;
    try {
      if (readdirSync(activePath).length !== 0) return false;
      const live = this.directoryIdentity(activePath);
      if (live === undefined || live.dev !== identity.dev || live.ino !== identity.ino)
        return false;
      rmdirSync(activePath);
      return true;
    } catch {
      return false;
    }
  }

  private cleanStaging(lock: CommitLock, now: number): boolean {
    const staging = this.stagingPath(lock);
    const info = lstatSafe(staging);
    if (info === undefined) return true;
    if (!info.isDirectory() || info.isSymbolicLink()) return false;
    let names: string[];
    try {
      names = readdirSync(staging).sort();
    } catch {
      return false;
    }
    if (
      names.length > FsTransaction.maxStagingClaims ||
      names.some((name) => this.parseStagingName(name) === undefined)
    )
      return false;
    for (const name of names) {
      const lease = this.parseStagingName(name);
      if (lease === undefined) return false;
      const candidate = join(staging, name);
      const candidateIdentity = this.directoryIdentity(candidate);
      const leasePath = this.leasePath(candidate, lease.owner);
      if (candidateIdentity === undefined || now < lease.reclaimAfter) return false;
      const contents = (() => {
        try {
          const childNames = readdirSync(candidate);
          if (childNames.length === 0) return "empty";
          if (childNames.length !== 1 || childNames[0] !== `lease.${lease.owner}.json`)
            return undefined;
          return this.parseLease(readFileSync(leasePath, "utf8"));
        } catch {
          return undefined;
        }
      })();
      if (
        contents !== "empty" &&
        (contents === undefined || this.leaseContents(contents) !== this.leaseContents(lease))
      )
        return false;
      const live = this.directoryIdentity(candidate);
      if (
        live === undefined ||
        live.dev !== candidateIdentity.dev ||
        live.ino !== candidateIdentity.ino ||
        !this.removeStagingCandidate(candidate, contents === "empty" ? undefined : leasePath)
      )
        return false;
    }
    return true;
  }

  private removeStagingCandidate(candidate: string, leasePath: string | undefined): boolean {
    try {
      if (leasePath !== undefined) {
        const info = lstatSync(leasePath, { bigint: true });
        if (!info.isFile() || info.isSymbolicLink() || info.nlink !== 1n) return false;
        rmSync(leasePath);
      }
      rmdirSync(candidate);
      return true;
    } catch {
      return false;
    }
  }

  private acquireCommitLock(): OwnedCommitLease | undefined {
    const lock = this.options.commitLock;
    if (lock === undefined) return undefined;
    this.ensureAnchor(lock);
    this.assertCommitDeadline();
    const now = Date.now();
    const leaseMs = lock.leaseMs ?? FsTransaction.commitLeaseMs;
    if (!Number.isSafeInteger(leaseMs) || leaseMs <= 0 || leaseMs > FsTransaction.commitLeaseMs)
      throw new FsTxnError("commit lock could not be verified");
    const expiresAt = Math.min(
      now + leaseMs,
      this.options.commitNotAfter ?? Number.MAX_SAFE_INTEGER,
    );
    if (expiresAt <= now) throw new FsTxnError("commit deadline expired");
    if (!this.cleanStaging(lock, now)) throw new FsTxnError("commit lock is already held");
    const existing = this.activeLease(lock);
    if (existing !== undefined) {
      if (now < existing.reclaimAfter || !this.removeOwnedActive(lock, existing))
        throw new FsTxnError("commit lock is already held");
    } else if (lstatSafe(this.activePath(lock)) !== undefined && !this.removeEmptyActive(lock)) {
      throw new FsTxnError("commit lock is already held");
    }
    const staging = this.stagingPath(lock);
    this.assertCommitDeadline();
    try {
      mkdirSync(staging, { recursive: true, mode: 0o700 });
    } catch {
      throw new FsTxnError("commit lock could not be verified");
    }
    if (this.directoryIdentity(staging) === undefined)
      throw new FsTxnError("commit lock could not be verified");
    const lease: CommitLease = {
      expiresAt,
      reclaimAfter: expiresAt + FsTransaction.recoveryGraceMs,
      owner: randomBytes(32).toString("hex"),
    };
    const candidate = join(staging, this.stagingName(lease));
    const candidateLease = this.leasePath(candidate, lease.owner);
    const leaseText = this.leaseContents(lease);
    try {
      this.assertCommitDeadline();
      mkdirSync(candidate, 0o700);
      this.assertCommitDeadline();
      writeFileSync(candidateLease, leaseText, { encoding: "utf8", flag: "wx", mode: 0o600 });
      this.syncLeasePath(candidateLease);
      this.syncLeasePath(candidate, true);
      this.assertCommitDeadline();
      renameSync(candidate, this.activePath(lock));
      this.syncLeasePath(this.anchorPath(lock), true);
    } catch (err) {
      this.removeStagingCandidate(
        candidate,
        lstatSafe(candidateLease) === undefined ? undefined : candidateLease,
      );
      if (err instanceof FsTxnError) throw err;
      throw new FsTxnError("commit lock is already held");
    }
    const owned = this.activeLease(lock);
    if (owned === undefined || owned.owner !== lease.owner || owned.leaseText !== leaseText) {
      this.removeStagingCandidate(candidate, candidateLease);
      throw new FsTxnError("commit lock could not be verified");
    }
    this.activeCommitLease = owned;
    return owned;
  }

  private releaseCommitLock(identity: OwnedCommitLease | undefined): void {
    const lock = this.options.commitLock;
    if (identity === undefined || lock === undefined) return;
    // Never delete the shared anchor or an active path by name. The only
    // deletions target this transaction's owner-named lease and its now-empty
    // directory; a successor or foreign entry makes rmdir fail closed.
    this.removeOwnedActive(lock, identity);
  }

  private validateWriteExpectation(write: StagedWrite): void {
    if (write.expect === undefined) return;
    const info = lstatSafe(write.path);
    if (info?.isSymbolicLink()) throw new FsTxnError("write target changed before commit");
    const live = info === undefined ? undefined : readFileSync(write.path, "utf8");
    const unchanged =
      "absent" in write.expect
        ? live === undefined
        : live !== undefined &&
          createHash("sha256").update(live, "utf8").digest("hex") === write.expect.sha256;
    if (!unchanged) throw new FsTxnError("write target changed before commit");
  }

  private syncDurableWrite(path: string, root: string | undefined): void {
    this.guardParents(path, root, false);
    this.assertCommitDeadline();
    const fd = openSync(path, fsConstants.O_RDWR);
    try {
      this.assertCommitDeadline();
      fsyncSync(fd);
    } finally {
      closeSync(fd);
    }
    if (process.platform !== "win32") {
      this.guardParents(path, root, false);
      this.assertCommitDeadline();
      const parentFd = openSync(dirname(path), fsConstants.O_RDONLY);
      try {
        this.assertCommitDeadline();
        fsyncSync(parentFd);
      } finally {
        closeSync(parentFd);
      }
    }
  }

  commit(): FsTxnResult {
    const applied: AppliedWrite[] = [];
    const removed: AppliedRemoval[] = [];
    // Collapse repeated writes to the same target (last wins) BEFORE committing:
    // staging one path twice would back up the first write as `<path>.aih.bak`, then
    // overwrite that backup with the second — making a later rollback non-restorative.
    const staged = dedupeByPath(this.staged);
    const removals = dedupeRemovals(this.stagedRemovals);
    const assertions = dedupeAssertions(this.stagedAssertions);
    // A path cannot be both written AND removed in one transaction — the on-disk
    // outcome (write, then move-to-legacy) would contradict the reported writes[].
    // No shipping command produces this; fail closed so a future one can't silently.
    const writePaths = new Set(staged.map((w) => w.path));
    for (const r of removals) {
      if (writePaths.has(r.path)) {
        throw new FsTxnError(`transaction both writes and removes the same path: ${r.path}`);
      }
    }
    for (const assertion of assertions) {
      if (writePaths.has(assertion.path) || removals.some((item) => item.path === assertion.path))
        throw new FsTxnError(
          `transaction both asserts and mutates the same path: ${assertion.path}`,
        );
    }
    let lockIdentity: OwnedCommitLease | undefined;
    let failed = false;
    try {
      lockIdentity = this.acquireCommitLock();
      this.assertCommitDeadline();
      for (const assertion of assertions) this.guardParents(assertion.path, assertion.root, false);
      validateAssertions(assertions);
      for (const w of staged) {
        this.ensureParents(w.path, w.root);
        // Refuse to write THROUGH an existing symlink — it can redirect the write
        // outside the repo, and copyFileSync would back up the link's TARGET, not the
        // link. Fail closed; the executor enforces parent-dir containment separately.
        const info = lstatSafe(w.path);
        if (info?.isSymbolicLink()) {
          throw new Error(`refusing to write through a symlink: ${w.path}`);
        }
        this.validateWriteExpectation(w);
        const existed = info !== undefined;
        const backupPath = `${w.path}.aih.bak`;
        const tmpPath = `${w.path}.aih.tmp`;
        // The temp + backup paths are followed by copyFileSync/writeFileSync, so a
        // pre-placed symlink THERE would redirect the write/copy outside the repo just
        // like a symlinked target. Reject a planted link and clear any stale scratch so
        // the exclusive create below can't be tricked into following one.
        clearScratch(backupPath, () => {
          this.guardParents(w.path, w.root, false);
          this.assertCommitDeadline();
        });
        clearScratch(tmpPath, () => {
          this.guardParents(w.path, w.root, false);
          this.assertCommitDeadline();
        });
        let backup: string | undefined;
        if (existed) {
          backup = backupPath;
          // Reads the just-written source; retry the transient Windows scanner lock.
          this.guardParents(w.path, w.root, false);
          this.assertCommitDeadline();
          retryTransient(() => {
            this.assertCommitDeadline();
            return copyFileSync(w.path, backupPath, fsConstants.COPYFILE_EXCL);
          });
        }
        this.guardParents(w.path, w.root, false);
        this.assertCommitDeadline();
        retryTransient(() => {
          this.assertCommitDeadline();
          return writeFileSync(tmpPath, w.contents, { encoding: "utf8", flag: "wx" });
        });
        if (w.mode !== undefined) {
          this.guardParents(w.path, w.root, false);
          this.assertCommitDeadline();
          chmodSync(tmpPath, w.mode);
        }
        // Renaming OVER the existing target is the classic Windows flake: the dest
        // handle may be briefly held by AV/the indexer right after the prior write.
        this.guardParents(w.path, w.root, false);
        this.validateWriteExpectation(w);
        const parentGuard = this.captureParentGuard(w.path, w.root);
        this.assertCommitDeadline();
        retryTransient(() => {
          this.assertCommitDeadline();
          return renameSync(tmpPath, w.path);
        });
        applied.push({
          path: w.path,
          contents: w.contents,
          backup,
          created: !existed,
          parentGuard,
        });
        this.guardParents(w.path, w.root, false);
        if (w.durable) this.syncDurableWrite(w.path, w.root);
      }
      // Removals commit AFTER writes so a partial failure rolls both back in order.
      for (const r of removals) {
        this.guardParents(r.path, r.root, false);
        const info = lstatSafe(r.path);
        if (info === undefined) continue; // already gone — idempotent no-op
        // Never MOVE a symlink: rollback would renameSync it back as-is, but a link
        // that pointed outside the repo has no place in .aih/legacy/ and restoring it
        // silently re-establishes the escape. The executor also rejects this earlier.
        if (info.isSymbolicLink()) {
          throw new Error(`refusing to remove a symlink: ${r.path}`);
        }
        if (r.expect !== undefined && !info.isFile()) {
          throw new FsTxnError(`removal target is not a regular file: ${r.path}`);
        }
        this.ensureParents(r.legacyPath, r.root);
        // NEVER overwrite an occupied destination — for BOTH modes. An aborted prune
        // rolls its move back (so it leaves nothing here), which means an existing file
        // at the dest is a COMPLETED prior rescue (or a write backup that may be the
        // ONLY copy of never-committed content); deleting it would destroy that copy.
        // The archive falls back to `<path>.N`; a hard-delete backup falls back to
        // `<path>.N.aih.bak` so every slot keeps matching the gitignored glob.
        const dest = r.backupSibling ? freeBackupDest(r.legacyPath) : freeLegacyDest(r.legacyPath);
        this.guardParents(r.path, r.root, false);
        this.guardParents(dest, r.root, false);
        const sourceParentGuard = this.captureParentGuard(r.path, r.root);
        const legacyParentGuard = this.captureParentGuard(dest, r.root);
        this.assertCommitDeadline();
        retryTransient(() => {
          this.assertCommitDeadline();
          return renameSync(r.path, dest);
        });
        removed.push({
          path: r.path,
          legacyPath: dest,
          sourceParentGuard,
          legacyParentGuard,
        });
        this.guardParents(r.path, r.root, false);
        this.guardParents(dest, r.root, false);
        if (r.expect !== undefined) {
          const moved = readRegularFile(dest);
          const actual =
            moved === undefined ? undefined : createHash("sha256").update(moved).digest("hex");
          if (actual !== r.expect.sha256) {
            throw new FsTxnError(`removal target changed before commit: ${r.path}`);
          }
        }
      }
      this.assertCommitDeadline();
      for (const assertion of assertions) this.guardParents(assertion.path, assertion.root, false);
      validateAssertions(assertions);
      this.assertCommitDeadline();
      return {
        written: applied.map((a) => a.path),
        backups: applied.flatMap((a) => (a.backup ? [a.backup] : [])),
        removed,
      };
    } catch (err) {
      failed = true;
      const preserved = [
        ...rollbackRemovals(removed, () => this.assertRollbackLease()),
        ...rollbackAppliedWrites(applied, () => this.assertRollbackLease()),
      ];
      const suffix =
        preserved.length === 0
          ? "was rolled back"
          : `preserved concurrent changes at ${preserved.join(", ")}`;
      throw new FsTxnError(`transaction failed and ${suffix}: ${(err as Error).message}`);
    } finally {
      if (failed) this.rollbackCreatedDirectories(() => this.assertRollbackLease());
      this.releaseCommitLock(lockIdentity);
      this.activeCommitLease = undefined;
    }
  }
}

function dedupeAssertions(staged: StagedAssertion[]): StagedAssertion[] {
  const byPath = new Map<string, StagedAssertion>();
  for (const assertion of staged) byPath.set(assertion.path, assertion);
  return [...byPath.values()];
}

function validateAssertions(assertions: StagedAssertion[]): void {
  for (const assertion of assertions) {
    const opened = readRegularFileWithStats(assertion.path);
    const actual =
      opened === undefined || opened.stats.nlink > 1
        ? undefined
        : createHash("sha256").update(opened.contents).digest("hex");
    if (actual !== assertion.sha256)
      throw new FsTxnError(`${assertion.describe} changed before commit`);
  }
}

/** Keep only the last staged removal per source path (deterministic). */
function dedupeRemovals(staged: StagedRemoval[]): StagedRemoval[] {
  const byPath = new Map<string, StagedRemoval>();
  for (const r of staged) byPath.set(r.path, r);
  return [...byPath.values()];
}

/**
 * A free legacy destination: `base` if nothing is there, else `base.1`, `base.2`, …
 * so a second rescue of a repopulated path never clobbers the first. Refuses a
 * symlink at any candidate (it would redirect the rename out of the repo).
 */
function freeLegacyDest(base: string): string {
  const check = (p: string): "free" | "file" => {
    const st = lstatSafe(p);
    if (st === undefined) return "free";
    if (st.isSymbolicLink()) throw new Error(`refusing to move onto a symlinked legacy path: ${p}`);
    return "file";
  };
  if (check(base) === "free") return base;
  for (let n = 1; n < 100000; n++) {
    const cand = `${base}.${n}`;
    if (check(cand) === "free") return cand;
  }
  throw new Error(`too many prior rescues at ${base}`);
}

/**
 * A free hard-delete backup destination: `<path>.aih.bak` if free, else
 * `<path>.1.aih.bak`, `<path>.2.aih.bak`, … — the counter sits BEFORE the suffix so
 * every fallback still matches the gitignored `*.aih.bak` glob. Same symlink refusal
 * and never-overwrite guarantee as {@link freeLegacyDest}: an existing backup may be
 * the only copy of never-committed content and is never destroyed.
 */
function freeBackupDest(base: string): string {
  const check = (p: string): "free" | "file" => {
    const st = lstatSafe(p);
    if (st === undefined) return "free";
    if (st.isSymbolicLink()) throw new Error(`refusing to move onto a symlinked backup path: ${p}`);
    return "file";
  };
  if (check(base) === "free") return base;
  const stem = base.endsWith(".aih.bak") ? base.slice(0, -".aih.bak".length) : base;
  for (let n = 1; n < 100000; n++) {
    const cand = `${stem}.${n}.aih.bak`;
    if (check(cand) === "free") return cand;
  }
  throw new Error(`too many prior backups at ${base}`);
}

/** Restore moved-out files by renaming them back from `.aih/legacy/` (best-effort). */
function rollbackRemovals(
  removed: AppliedRemoval[],
  assertCanMutate: () => void = () => {},
): string[] {
  const preserved: string[] = [];
  for (const r of [...removed].reverse()) {
    try {
      if (
        parentGuardMatches(r.sourceParentGuard) &&
        parentGuardMatches(r.legacyParentGuard) &&
        existsSync(r.legacyPath) &&
        !existsSync(r.path)
      ) {
        assertCanMutate();
        if (!parentGuardMatches(r.sourceParentGuard)) continue;
        assertCanMutate();
        mkdirSync(dirname(r.path), { recursive: true });
        if (!parentGuardMatches(r.sourceParentGuard) || !parentGuardMatches(r.legacyParentGuard))
          continue;
        assertCanMutate();
        renameSync(r.legacyPath, r.path);
      } else {
        preserved.push(r.path);
      }
    } catch {
      preserved.push(r.path);
    }
  }
  return [...new Set(preserved)];
}

function parentGuardMatches(guard: ParentGuard | undefined): boolean {
  if (guard === undefined) return true;
  for (const directory of guard.directories) {
    try {
      const stats = lstatSync(directory.path, { bigint: true });
      if (
        !stats.isDirectory() ||
        stats.isSymbolicLink() ||
        stats.dev === 0n ||
        stats.ino === 0n ||
        stats.dev !== directory.dev ||
        stats.ino !== directory.ino
      ) {
        return false;
      }
    } catch {
      return false;
    }
  }
  return true;
}

/** Keep only the last staged write per target path (deterministic, insertion order). */
function dedupeByPath(staged: StagedWrite[]): StagedWrite[] {
  const byPath = new Map<string, StagedWrite>();
  for (const w of staged) byPath.set(w.path, w);
  return [...byPath.values()];
}

/** `lstat` (does not follow links) or `undefined` if the path does not exist. */
function lstatSafe(path: string): Stats | undefined {
  try {
    return lstatSync(path);
  } catch {
    return undefined;
  }
}

/**
 * Prepare a `.aih.tmp` / `.aih.bak` scratch path for an exclusive create: fail
 * closed if a symlink was planted there (it would redirect the write/copy out of
 * the repo), and remove a stale REGULAR leftover from a prior aborted run so the
 * exclusive create doesn't `EEXIST`. Never follows or deletes through a link.
 */
function clearScratch(path: string, assertCommitDeadline: () => void): void {
  const st = lstatSafe(path);
  if (st === undefined) return;
  if (st.isSymbolicLink()) {
    throw new Error(`refusing to write through a symlinked scratch path: ${path}`);
  }
  assertCommitDeadline();
  rmSync(path, { force: true });
}

/**
 * Restore only targets that still contain this transaction's generated bytes.
 * A later operator edit is never overwritten during best-effort rollback; its
 * pre-transaction backup remains beside the target for recovery.
 */
/**
 * Exported for direct unit testing: a real concurrent write is not schedulable
 * deterministically between this synchronous transaction's filesystem calls.
 */
export function rollbackAppliedWrites(
  applied: AppliedWrite[],
  assertCanMutate: () => void = () => {},
): string[] {
  const preserved: string[] = [];
  for (const a of [...applied].reverse()) {
    try {
      if (!parentGuardMatches(a.parentGuard)) {
        preserved.push(a.path);
        continue;
      }
      const info = lstatSafe(a.path);
      const current =
        info === undefined || info.isSymbolicLink() ? undefined : readFileSync(a.path, "utf8");
      if (a.created) {
        if (current === a.contents && parentGuardMatches(a.parentGuard)) {
          assertCanMutate();
          rmSync(a.path, { force: true });
        } else if (current === a.contents) {
          preserved.push(a.path);
        } else if (current !== undefined) preserved.push(a.path);
      } else if (a.backup && existsSync(a.backup)) {
        if (current === a.contents && restoreOverwrittenWrite(a, assertCanMutate)) {
          continue;
        }
        preserved.push(a.path);
      }
    } catch {
      preserved.push(a.path);
    }
  }
  return [...new Set(preserved)];
}

/**
 * Restore a backed-up file without ever copying through the mutable destination
 * leaf. Node exposes only path-based primitives, so its lstat/read/rename checks
 * retain a bounded non-atomic race; every check is repeated immediately before
 * rename and a swapped leaf is preserved rather than followed.
 */
function restoreOverwrittenWrite(applied: AppliedWrite, assertCanMutate: () => void): boolean {
  if (applied.backup === undefined) return false;
  if (!parentGuardMatches(applied.parentGuard)) return false;
  const backup = readRegularFile(applied.backup);
  if (!parentGuardMatches(applied.parentGuard)) return false;
  if (backup === undefined) return false;
  const tmpPath = `${applied.path}.aih.rollback.tmp`;
  if (!clearRollbackScratch(tmpPath, applied.parentGuard, assertCanMutate)) return false;
  try {
    if (!parentGuardMatches(applied.parentGuard)) return false;
    assertCanMutate();
    writeFileSync(tmpPath, backup, { flag: "wx" });
    if (!parentGuardMatches(applied.parentGuard)) return false;
    const live = lstatSafe(applied.path);
    if (live === undefined || live.isSymbolicLink()) return false;
    const current = readFileSync(applied.path, "utf8");
    if (current !== applied.contents || !parentGuardMatches(applied.parentGuard)) return false;
    // Repeat the leaf check immediately before atomic replacement. `rename` replaces
    // a symlink entry itself rather than following it, unlike `copyFileSync`.
    const final = lstatSafe(applied.path);
    if (final === undefined || final.isSymbolicLink()) return false;
    if (readFileSync(applied.path, "utf8") !== applied.contents) return false;
    if (!parentGuardMatches(applied.parentGuard)) return false;
    assertCanMutate();
    renameSync(tmpPath, applied.path);
    const backupInfo = lstatSafe(applied.backup);
    if (
      backupInfo !== undefined &&
      !backupInfo.isSymbolicLink() &&
      parentGuardMatches(applied.parentGuard)
    ) {
      assertCanMutate();
      rmSync(applied.backup, { force: true });
    }
    return true;
  } catch {
    return false;
  } finally {
    clearRollbackScratch(tmpPath, applied.parentGuard, assertCanMutate);
  }
}

function clearRollbackScratch(
  path: string,
  parentGuard: ParentGuard | undefined,
  assertCanMutate: () => void,
): boolean {
  if (!parentGuardMatches(parentGuard)) return false;
  const info = lstatSafe(path);
  if (info === undefined) return true;
  if (info.isSymbolicLink()) return false;
  try {
    if (!parentGuardMatches(parentGuard)) return false;
    assertCanMutate();
    rmSync(path, { force: true });
    return true;
  } catch {
    return false;
  }
}

/** Read a file's text, or `undefined` if it does not exist. */
export function readIfExists(path: string): string | undefined {
  // A read issued right after the file was written (e.g. a second `executePlan`
  // re-reading what the first just laid down) hits the same transient Windows lock
  // window as the write side, so it gets the same bounded retry.
  return existsSync(path) ? retryTransient(() => readFileSync(path, "utf8")) : undefined;
}

/** `O_NOFOLLOW` where the platform has it (absent at runtime on Windows despite the typings). */
const O_NOFOLLOW = (fsConstants as Record<string, number | undefined>).O_NOFOLLOW ?? 0;
const HAS_O_NOFOLLOW = O_NOFOLLOW !== 0;
/** `O_NONBLOCK` where exposed; a no-op for regular files and prompt refusal for FIFOs. */
const O_NONBLOCK = (fsConstants as Record<string, number | undefined>).O_NONBLOCK ?? 0;

/**
 * Open-then-read on ONE file descriptor: the regular-file check (`fstat` on the
 * open fd, never a second path lookup) and the read cannot be raced apart.
 * Where the platform exposes `O_NOFOLLOW`, a symlink swapped in after directory
 * enumeration is refused at open rather than silently followed. Where it does
 * not, the fallback verifies after opening that the path still names the same
 * non-symlink regular file as the descriptor before reading. Returns undefined
 * for anything that is not a readable regular file.
 *
 * Use this — not {@link readIfExists} — for any path DISCOVERED by a directory
 * scan: a plain exists-then-read pair on a scanned path is a swap window where
 * a symlink planted between enumeration and read gets silently followed and its
 * target's bytes laundered into an artifact (marketplace build, evidence
 * bundle, fleet bundle all package what they read).
 */
export function readRegularFileWithStats(
  abs: string,
  options: { maxBytes?: number } = {},
): { contents: Buffer; stats: Stats } | undefined {
  let fd: number;
  try {
    fd = openSync(abs, fsConstants.O_RDONLY | O_NOFOLLOW | O_NONBLOCK, 0o600);
  } catch {
    return undefined;
  }
  try {
    const stats = fstatSync(fd);
    if (!stats.isFile()) return undefined;
    if (options.maxBytes !== undefined && stats.size > options.maxBytes) return undefined;
    if (!HAS_O_NOFOLLOW && !openedPathStillNamesFile(abs, fd)) return undefined;
    const contents =
      options.maxBytes === undefined
        ? readFileSync(fd)
        : readBoundedFileDescriptor(fd, options.maxBytes);
    return contents === undefined ? undefined : { contents, stats };
  } finally {
    closeSync(fd);
  }
}

/**
 * Read at most `maxBytes + 1` bytes from an already-open descriptor. The extra
 * byte distinguishes an exact-boundary file from one that grew after an earlier
 * `fstat`; returning `undefined` keeps the caller's byte cap effective during
 * the read instead of only before it.
 */
export function readBoundedFileDescriptor(fd: number, maxBytes: number): Buffer | undefined {
  if (!Number.isSafeInteger(maxBytes) || maxBytes < 0)
    throw new RangeError("maxBytes must be a non-negative safe integer");
  const chunks: Buffer[] = [];
  let total = 0;
  while (total <= maxBytes) {
    const chunk = Buffer.allocUnsafe(Math.min(64 * 1024, maxBytes - total + 1));
    const bytesRead = readSync(fd, chunk, 0, chunk.length, null);
    if (bytesRead === 0) return Buffer.concat(chunks, total);
    total += bytesRead;
    if (total > maxBytes) return undefined;
    chunks.push(bytesRead === chunk.length ? chunk : chunk.subarray(0, bytesRead));
  }
  return undefined;
}

function openedPathStillNamesFile(path: string, fd: number): boolean {
  let opened: BigIntStats;
  let current: BigIntStats;
  try {
    opened = fstatSync(fd, { bigint: true });
    current = lstatSync(path, { bigint: true });
  } catch {
    return false;
  }
  if (!opened.isFile() || current.isSymbolicLink() || !current.isFile()) return false;
  return sameBigIntFileIdentity(opened, current);
}

function sameBigIntFileIdentity(
  a: Pick<BigIntStats, "dev" | "ino">,
  b: Pick<BigIntStats, "dev" | "ino">,
): boolean {
  if (a.dev !== b.dev) return false;
  if (a.ino === 0n || b.ino === 0n) return false;
  return a.ino === b.ino;
}

export function readRegularFile(
  abs: string,
  options: { maxBytes?: number } = {},
): Buffer | undefined {
  return readRegularFileWithStats(abs, options)?.contents;
}
