import { frontmatter, lines } from "../internals/render.js";
import type { RepoStack } from "./scan.js";

/**
 * Render the generated artifacts for a profiled repo. These are deterministic
 * string builders (no dates, stable ordering) so golden-file tests stay stable.
 * `CLAUDE.md` is a THIN pointer (< 30 lines) into the canonical context dir; the
 * `.mdc` files carry the stack-specific rules a model should follow.
 */

/** "—" placeholder when a command could not be inferred from signature files. */
const UNKNOWN = "(not detected — set manually)";

function languageList(stack: RepoStack): string {
  return stack.languages.length > 0 ? stack.languages.join(", ") : "none detected";
}

function deploymentList(stack: RepoStack): string {
  return stack.deployment.length > 0 ? stack.deployment.join(", ") : "none detected";
}

/**
 * The thin `CLAUDE.md` adapter: a pointer, never the rulebook. Opens with the
 * canonical "This file is not the full rulebook." line, routes to `contextDir`,
 * surfaces the detected Build/Test/Lint commands, and lists a couple of
 * guardrails. Stays comfortably under 30 lines.
 */
export function renderClaudeMd(stack: RepoStack, contextDir: string): string {
  return lines(
    "# Project guide for AI agents",
    "",
    "This file is not the full rulebook. It is a pointer generated by `aih profile`.",
    `The canonical rules, architecture, and context live in \`${contextDir}/\` and`,
    "`.cursor/rules/`. Read those before making non-trivial changes.",
    "",
    "## Detected stack",
    "",
    `- Languages: ${languageList(stack)}`,
    `- Deployment: ${deploymentList(stack)}`,
    "",
    "## Commands",
    "",
    `- Test: \`${stack.testRunner ?? UNKNOWN}\``,
    `- Build: \`${stack.buildCommand ?? UNKNOWN}\``,
    `- Lint: \`${stack.lintCommand ?? UNKNOWN}\``,
    "",
    "## Guardrails",
    "",
    "- Run the test command above before claiming a change works.",
    `- Keep this file thin; put durable guidance in \`${contextDir}/\`.`,
  );
}

/**
 * The primary Cursor rule: a stack summary plus the detected commands. It carries
 * a broad glob but keeps `alwaysApply: false`, so it attaches by description
 * relevance rather than firing on every file.
 */
export function renderStackMdc(stack: RepoStack): string {
  const fm = frontmatter({
    description: "Detected project stack and canonical build/test/lint commands.",
    globs: ["**/*"],
    alwaysApply: false,
  });
  return lines(
    fm,
    "",
    "# Stack",
    "",
    `Languages: ${languageList(stack)}.`,
    `Deployment: ${deploymentList(stack)}.`,
    "",
    "# Commands",
    "",
    `- Test with \`${stack.testRunner ?? UNKNOWN}\`.`,
    `- Build with \`${stack.buildCommand ?? UNKNOWN}\`.`,
    `- Lint with \`${stack.lintCommand ?? UNKNOWN}\`.`,
    "",
    "Prefer these exact commands over guessing equivalents.",
  );
}

/** TypeScript-specific Cursor rule, emitted only when a TS/Node stack is detected. */
export function renderTypescriptMdc(): string {
  const fm = frontmatter({
    description: "TypeScript and Node.js conventions for this repository.",
    globs: ["**/*.ts", "**/*.tsx"],
    alwaysApply: false,
  });
  return lines(
    fm,
    "",
    "# TypeScript",
    "",
    "- Add explicit parameter and return types to exported functions.",
    "- Avoid `any`; narrow `unknown` at boundaries with type guards or zod.",
    "- Use immutable updates (spread / new objects) instead of mutation.",
    "- Handle errors explicitly; never silently swallow a rejection.",
  );
}

/**
 * EF Core async rules, emitted only when a .NET stack is detected (per the
 * blueprint). Mirrors the canonical guidance: async DB access, no sync-over-async,
 * `AsNoTracking` for reads.
 */
export function renderEfCoreMdc(): string {
  const fm = frontmatter({
    description: "Entity Framework Core async data-access rules for .NET code.",
    globs: ["**/*.cs"],
    alwaysApply: false,
  });
  return lines(
    fm,
    "",
    "# EF Core async",
    "",
    "- Use the async APIs (`ToListAsync`, `FirstOrDefaultAsync`, `SaveChangesAsync`).",
    "- Never block on a Task with `.Result` or `.Wait()` (no sync-over-async).",
    "- Use `AsNoTracking()` for read-only queries.",
    "- Pass a `CancellationToken` through async data-access methods.",
  );
}
