import {
  type Action,
  AihError,
  digest,
  doc,
  type FrameworkComponentsV1,
  type FrameworkHookControlPlanV1,
  type FrameworkOperationContextV1,
  type FrameworkVerifiedSourceV1,
  lines,
  type Plan,
  type PlanResult,
  plan,
  writeText,
} from "@aihq/core/framework-host";
import { readSuperpowersDescriptor, type SuperpowersDescriptor } from "./descriptor.js";
import { superpowersActionsForCli, superpowersOverviewDoc } from "./guidance.js";
import { planHookControls } from "./hooks.js";
import { KIRO_STEERING_PATH, REF_ENVIRONMENT_VARIABLE, UPSTREAM } from "./identity.js";
import { methodologySteering } from "./kiro-steering.js";

const FULL_SHA = /^[a-f0-9]{40}$/;

/** The exact commit to verify: the descriptor's pin, or an exact `AIH_SUPERPOWERS_REF` override. */
function requestedCommit(
  ctx: FrameworkOperationContextV1,
  descriptor: SuperpowersDescriptor,
): string {
  const requested = (ctx.env[REF_ENVIRONMENT_VARIABLE] ?? "").trim();
  if (requested.length > 0 && !FULL_SHA.test(requested)) {
    throw new AihError(
      "AIH_SUPERPOWERS_REF must be an exact lowercase 40-character commit SHA for evidence-gated installs",
      "AIH_CONFIG",
    );
  }
  return requested || descriptor.source.commit;
}

function componentsFor(
  ctx: FrameworkOperationContextV1,
  descriptor: SuperpowersDescriptor,
): FrameworkComponentsV1 {
  // Every targeted host except Kiro receives upstream Superpowers guidance; Kiro
  // receives aih's own methodology bridge instead of vendor bytes.
  const hosts = ctx.targets.filter((target) => target !== "kiro");
  return {
    frameworkId: "superpowers",
    upstream: { repository: UPSTREAM.repository, commit: descriptor.source.commit },
    components: descriptor.components.map((component) => ({
      id: component.id,
      paths: component.paths,
      hosts,
    })),
  };
}

/** Every pinned component, with the targeted hosts it applies to. */
export function identifyComponents(ctx: FrameworkOperationContextV1): FrameworkComponentsV1 {
  return componentsFor(ctx, readSuperpowersDescriptor(ctx.descriptor));
}

/** The guidance plan, built only after Core's evidence gate verified the exact source. */
function verifiedGuidancePlan(
  ctx: FrameworkOperationContextV1,
  verified: FrameworkVerifiedSourceV1,
  commit: string,
  hookControls: FrameworkHookControlPlanV1 | undefined,
): Plan {
  const pin = verified.authorizations[0]?.pinnedSha ?? commit;
  const actions: Action[] = ctx.targets.flatMap((cli) => superpowersActionsForCli(cli, pin));
  if (ctx.targets.includes("kiro")) {
    actions.push(
      writeText(
        KIRO_STEERING_PATH,
        methodologySteering(),
        "Kiro steering: first-party aih methodology bridge (not Superpowers vendor bytes)",
      ),
      doc(
        "Kiro methodology bridge provenance",
        "The Kiro steering file is generated by aih and is not labeled as obra/Superpowers vendor evidence.",
      ),
    );
  }
  if (hookControls !== undefined) actions.push(...hookControls.actions);
  actions.push(
    superpowersOverviewDoc(),
    doc(
      "Superpowers verified source",
      `aih verified the selected components from ${verified.sourceRoot.replace(/\\/g, "/")} at exact commit ${pin}; the quarantine is removed after this command.`,
    ),
    digest(
      "Superpowers baseline evidence authorizations",
      lines(
        "Superpowers component evidence receipts:",
        ...verified.authorizations.map(
          (receipt) =>
            `- ${receipt.componentId} — ${receipt.tier} · ${receipt.pinnedSha.slice(0, 12)} · ${receipt.treeSha256.slice(0, 12)}`,
        ),
      ),
      { authorizations: [...verified.authorizations] },
    ),
  );
  return plan("superpowers: verified guidance", ...actions);
}

/**
 * `aih superpowers`: ask Core's evidence gate to acquire obra/Superpowers at the
 * exact pin and verify every component, then emit evidence-bound guidance for
 * the targeted hosts (and the Kiro steering bridge). No install is executed.
 */
export async function executeSuperpowers(ctx: FrameworkOperationContextV1): Promise<PlanResult> {
  const descriptor = readSuperpowersDescriptor(ctx.descriptor);
  const commit = requestedCommit(ctx, descriptor);
  const hookControls =
    ctx.policy.hookControls.disabled.length === 0
      ? undefined
      : planHookControls(ctx, ctx.policy.hookControls);
  const identified = componentsFor(ctx, descriptor);
  return ctx.host.runEvidenceGatedInstall({
    source: { owner: descriptor.source.owner, repo: descriptor.source.repo, commit },
    components: descriptor.components,
    componentIds: identified.components.map((component) => component.id),
    buildInstallPlan: (verified) => verifiedGuidancePlan(ctx, verified, commit, hookControls),
  });
}
