import { mkdir, rename, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";

import { canonicalStrictJsonSha256V1 } from "../src/contract/strict-json-v1.js";
import {
  admitDefaultCatalogPreassemblyV1,
  createDefaultCatalogPreassemblyV1,
} from "../src/org-policy/workbench/default-catalog-preassembly.js";
import {
  admitDefaultStudioPreassemblyV1,
  buildDefaultStudioPackageBaseV1,
  createDefaultStudioPreassemblyV1,
} from "../src/org-policy/studio-model.js";
import { compilePackagedWorkbenchCatalogForBuildV1 } from "../src/org-policy/workbench/prepared-catalog.js";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const companionPath = "src/org-policy/workbench/default-catalog-preassembly.generated.cjs";
const nodeRequire = createRequire(import.meta.url);

function generatedModule(
  catalog: Readonly<{ bytes: string; sha256: string }>,
  studio: Readonly<{ bytes: string; sha256: string }>,
): string {
  return `module.exports = ${JSON.stringify({ catalog, studio })};\n`;
}

function samePreparedOutput(
  left: ReturnType<typeof compilePackagedWorkbenchCatalogForBuildV1>,
  right: ReturnType<typeof compilePackagedWorkbenchCatalogForBuildV1>,
): boolean {
  return canonicalStrictJsonSha256V1(left) === canonicalStrictJsonSha256V1(right);
}

/**
 * The current compiler is deliberately invoked before this companion path is read or written.
 * A provider code edit that keeps its version can therefore never let stale generated bytes drive
 * the build: staged bytes must be admitted and equal this fresh uncached output first.
 */
export async function buildWorkbenchPreassembly(root = repositoryRoot) {
  const fresh = compilePackagedWorkbenchCatalogForBuildV1();
  const catalog = createDefaultCatalogPreassemblyV1(fresh);
  const freshStudio = buildDefaultStudioPackageBaseV1(fresh);
  const studio = createDefaultStudioPreassemblyV1(freshStudio);
  const target = resolve(root, companionPath);
  const staging = `${target}.${process.pid}.staging.cjs`;
  await mkdir(dirname(target), { recursive: true });
  try {
    await writeFile(staging, generatedModule(catalog, studio), "utf8");
    delete nodeRequire.cache[staging];
    const staged = nodeRequire(staging) as unknown;
    if (
      staged === null ||
      typeof staged !== "object" ||
      Array.isArray(staged) ||
      !Object.hasOwn(staged, "catalog") ||
      !Object.hasOwn(staged, "studio")
    )
      throw new TypeError("Default catalog preassembly staging companion is malformed");
    const candidate = staged as { catalog: typeof catalog; studio: typeof studio };
    const admitted = admitDefaultCatalogPreassemblyV1(candidate.catalog);
    const admittedStudio = admitDefaultStudioPreassemblyV1(candidate.studio);
    if (
      admitted === undefined ||
      admittedStudio === undefined ||
      !samePreparedOutput(admitted, fresh) ||
      canonicalStrictJsonSha256V1(admittedStudio) !== canonicalStrictJsonSha256V1(freshStudio)
    )
      throw new TypeError("Default catalog preassembly staging output differs from current compiler");
    await rename(staging, target);
    return {
      bytes: Buffer.byteLength(catalog.bytes, "utf8") + Buffer.byteLength(studio.bytes, "utf8"),
      digest: studio.sha256,
      target: pathToFileURL(target).href,
    };
  } catch (error) {
    await rm(staging, { force: true }).catch(() => undefined);
    throw error;
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const result = await buildWorkbenchPreassembly();
  console.log(`Default catalog preassembly: ${String(result.bytes)} bytes ${result.digest}`);
}
