import { lines } from "../internals/render.js";
import { blockingLicenses } from "./sca.js";

/**
 * The platform-engineering control taxonomy the blueprint defines: Golden Paths
 * (paved, recommended routes), Guardrails (preventive limits), and Safety Nets
 * (detective fallbacks). Written into the canonical context dir so humans and
 * agents share one vocabulary for "what's enforced vs. what's recommended".
 */

/** Render the Golden Paths / Guardrails / Safety Nets taxonomy markdown. */
export function taxonomyDoc(): string {
  const blocking = blockingLicenses().join(", ");
  return lines(
    "# Control Taxonomy: Golden Paths, Guardrails, and Safety Nets",
    "",
    "> Generated by `aih guardrails`. This is the shared vocabulary for what is",
    "> *recommended* versus what is *enforced* in this repository.",
    "",
    "Platform-engineering controls fall into three layers. Golden Paths make the",
    "right thing easy; Guardrails make the wrong thing hard; Safety Nets catch what",
    "slips through. A healthy platform invests in all three.",
    "",
    "## Golden Paths (paved roads)",
    "",
    "The recommended, supported way to do a thing. Opt-in, not enforced — they win",
    "by being the path of least resistance.",
    "",
    "- Scaffolded project templates and a vetted dependency baseline.",
    "- A single secret-scanning config (`.gitleaks.toml`) shared by local hooks and CI.",
    "- Documented, reproducible build and release commands.",
    "",
    "## Guardrails (preventive controls)",
    "",
    "Hard limits that stop a class of mistake *before* it lands. Enforced, blocking.",
    "",
    "- **Pre-commit secret scan** — `.githooks/pre-commit` runs the pinned",
    "  `.pre-commit-config.yaml` hooks after `git config core.hooksPath .githooks`;",
    "  a detected secret blocks the commit.",
    "- **CI license gate** — `.github/workflows/sca.yml` fails the build on strong /",
    `  network copyleft (${blocking}).`,
    "- **Branch protection** — required status checks must pass before merge.",
    "",
    "## Safety Nets (detective controls)",
    "",
    "Fallbacks that catch what prevention misses. They detect and alert rather than",
    "block, so an incident is found fast even when a guardrail was bypassed.",
    "",
    "- Scheduled full-history secret scans (catch anything committed pre-policy).",
    "- Dependency / SBOM drift monitoring and vulnerability alerts.",
    "- Audit logging and anomaly alerts on the protected branches.",
    "",
    "## Machine-readable policy (this directory)",
    "",
    "The prose above *describes*; these sibling files *encode* the policy as data:",
    "",
    "- **`command-policy.md`** — the deny / ask / safe command lexicon, projected into",
    "  `.claude/settings.json` permissions and the sandbox `commandPolicy` where a",
    "  native seam exists, and documented for every other tool (advisory there).",
    "- **`risk-gates.json`** — the high-risk change categories (ask-not-deny),",
    "  CI-checkable so a pipeline can diff a PR's touched paths/commands against them.",
    "",
    "## How they relate",
    "",
    "| Layer | Posture | Failure mode | Example here |",
    "| --- | --- | --- | --- |",
    "| Golden Path | Recommended | Ignored | Project templates |",
    "| Guardrail | Enforced (block) | Friction | gitleaks pre-commit, license gate |",
    "| Safety Net | Detective (alert) | Noise | Full-history scans, SBOM drift |",
  );
}
